apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-account
  labels:
    app: tech-challenge-account
spec:
  template:
    metadata:
      name: tech-challenge-account
      labels:
        app: tech-challenge-account
    spec:
      containers:
        - name: tech-challenge-account-api
          image: 767397892937.dkr.ecr.us-east-1.amazonaws.com/account-service:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-account-secret
                  key: SPRING_DATASOURCE_URL
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-account-secret
                  key: DATASOURCE_USERNAME
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-account-secret
                  key: DATASOURCE_PASSWORD
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-account