apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-account-secret
type: Opaque
data:
  DATABASE_URL: amRiYzpwb3N0Z3Jlc3FsOmRhdGFiYXNlLTEuYzEwZ2lpZW04Ymh5LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  USERNAME: cG9zdGdyZXM=
  PASSWORD: cG9zdGdyZXM=